apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-head
spec:
  template:
    spec:
      containers:
      - name: vllm-head
        resources:
          limits:
            nvidia.com/gpu: 2
          requests:
            nvidia.com/gpu: 2
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vllm-worker
spec:
  template:
    spec:
      containers:
      - name: vllm-worker
        resources:
          limits:
            nvidia.com/gpu: 2
          requests:
            nvidia.com/gpu: 2
