
---
- name: Post-installation-steps
  hosts: master_main
  become: true
  
  tasks:
    - name: Install Calico operator
      command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml
      
    - name: Download Calico custom resources file
      get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/custom-resources.yaml
        dest: /tmp/custom-resources.yaml
        
    - name: Update CIDR in custom resources
      replace:
        path: /tmp/custom-resources.yaml
        regexp: 'cidr: 192\.168\.0\.0\/16'
        replace: 'cidr: 10.244.0.0/16'
        
    - name: Apply Calico custom resources
      command: kubectl create -f /tmp/custom-resources.yaml

    - name: Apply calico latest
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml 

    - name: enable scheduling on control-plane
      command: kubectl taint nodes $(kubectl get nodes --selector=node-role.kubernetes.io/control-plane -o jsonpath='{.items[*].metadata.name}') node-role.kubernetes.io/control-plane:NoSchedule-

    - name: Create standard storageclass
      copy:
        content: |
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: standard
          provisioner: kubernetes.io/no-provisioner
          volumeBindingMode: WaitForFirstConsumer
        dest: /tmp/storageclass.yaml
        
    - name: Apply Storageclass
      command: kubectl apply -f /tmp/storageclass.yaml