apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

configMapGenerator:
  - name: api-config
    behavior: merge
    literals:
      - AllowedWebsites=http://test.local
  - name: ui-config
    behavior: merge
    literals:
      - VITE_API_URL=http://test.local/api
  - name: console-config
    behavior: merge
    literals:
      - Host_FileConfig_Input=/root/testconsole
      - Host_FileConfig_Output=/root/testconsole/outd

patchesStrategicMerge:
  # Add environment specific patches here
  # - patches/increase-replica-count.yaml
  # - patches/set-resource-limits.yaml