---
- name: Kubernetes System and Network Setup
  hosts: all
  become: true
  
  tasks:
    # Basic system setup
    - name: Disable swap memory
      command: swapoff -a
      
    - name: Remove swap entries from fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
        
    - name: Disable UFW firewall
      service:
        name: ufw
        state: stopped
        enabled: false

    # Network setup
    - name: Create k8s kernel modules config
      copy:
        content: |
          overlay
          br_netfilter
        dest: /etc/modules-load.d/k8s.conf
        mode: '0644'
        
    - name: Load kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter
        
    - name: Create sysctl config for k8s
      copy:
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
        dest: /etc/sysctl.d/k8s.conf
        mode: '0644'
        
    - name: Apply sysctl parameters
      command: sysctl --system

    # Install GPU drivers
    - name: Install Ubuntu drivers
      apt:
        name:
          - ubuntu-drivers-common
        state: present
        update_cache: yes

    - name: Auto install recommended drivers
      command: ubuntu-drivers autoinstall
      register: driver_install
      
    - name: Set reboot flag if drivers were installed
      set_fact:
        reboot_required: true
      when: driver_install.changed

    - name: Reboot if required
      reboot:
      when: reboot_required is defined and reboot_required