# api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapi
  template:
    metadata:
      labels:
        app: testapi
    spec:
      containers:
      - name: testapi
        image: localhost:5000/testapi:latest
        ports:
        - containerPort: 8080
        - containerPort: 8081
        env:
        - name: ConnectionStrings__TestContext
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: ConnectionStrings__TestContext