# console-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testconsole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testconsole
  template:
    metadata:
      labels:
        app: testconsole
    spec:
      containers:
      - name: testconsole
        image: localhost:5000/testconsole:latest
        volumeMounts:
        - name: input-volume
          mountPath: /input
        - name: output-volume
          mountPath: /output
      volumes:
      - name: input-volume
        hostPath:
          path: /root/testconsole/input
      - name: output-volume
        hostPath:
          path: /root/testconsole/output