# deployments/ui-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testui
  template:
    metadata:
      labels:
        app: testui
    spec:
      containers:
      - name: testui
        image: localhost:5000/testui:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: ui-config
              key: VITE_API_URL