version: '3.8'

services:
  vllm:
    build:
      context: .
      dockerfile: Dockerfile
    image: vllm-tensor:latest
    user: root
    environment:
      - NCCL_DEBUG=INFO
      - NCCL_SOCKET_IFNAME=eth0
    volumes:
      - /root/.cache/huggingface:/root/.cache/huggingface
      - /dev/shm:/dev/shm
    runtime: nvidia
    command: ["/vllm-workspace/start.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [gpu]

volumes:
  huggingface-cache:
    driver: local