version: '3.8'

services:
  vllm:
    build:
      context: ../../../../../
      dockerfile: deployment/docker/GPU/vllm/02-vllm/Dockerfile
    image: vllm-tce:latest
    user: root
    environment:
      - NCCL_DEBUG=INFO
      - NCCL_SOCKET_IFNAME=eth0
      - NCCL_IGNORE_DISABLED_P2P=1
      - NCCL_P2P_DISABLE=1
    volumes:
      - /root/.cache/huggingface:/root/.cache/huggingface
      - /dev/shm:/dev/shm
    runtime: nvidia
    command: ["/vllm-workspace/start.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [gpu]

volumes:
  huggingface-cache:
    driver: local