FROM postgres:latest AS waitdb

USER root

RUN apt-get update && apt-get install -y \
    postgresql-client\
    && rm -rf /var/lib/apt/lists/*

COPY ./scripts /scripts

RUN chmod +x /scripts/wait-and-run-pg.sh

CMD /scripts/wait-and-run-pg.sh
#  && tail -f /dev/null
