apiVersion: v1
kind: Service
metadata:
  name: vllm-service
spec:
  type: NodePort
  selector:
    component: head
  ports:
  - protocol: TCP
    port: 8000
    targetPort: vllm
    name: vllm
    nodePort: 30080
