apiVersion: apps/v1
kind: Deployment
metadata:
  name: head
spec:
  replicas: 1
  selector:
    matchLabels:
      component: head
  template:
    metadata:
      labels:
        component: head
    spec:
      nodeSelector:
        role: master
      containers:
      - name: vllm-head
        image: vllm/vllm-openai:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
          name: ray
        - containerPort: 8080
          name: vllm
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: huggingface-cache
          mountPath: /root/.cache/huggingface
        - name: benchmarks
          mountPath: /vllm-workspace/examples
        - name: dshm
          mountPath: /dev/shm
        command:
          - "/bin/sh"
          - "-c"
          - |
            ray start --head --port=6379 --block &
            sleep 30 &&
            python3 -m vllm.entrypoints.openai.api_server \
              --port 8080 \
              --trust-remote-code \
              --served-model-name ministral \
              --model mistralai/Ministral-8B-Instruct-2410 \
              --gpu-memory-utilization 0.99 \
              --tensor-parallel-size 1 \
              --pipeline-parallel-size 2 \
              --dtype half & \
            tail -f /dev/null
      volumes:
      - name: huggingface-cache
        hostPath:
          path: /root/.cache/huggingface
      - name: benchmarks
        hostPath:
          path: /root/TCE-Kubernetes-scripts/benchmark-scripts/
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 25Gi
