apiVersion: v1
kind: Service
metadata:
  name: head-service
spec:
  type: ClusterIP
  selector:
    component: head
  ports:
  - protocol: TCP
    port: 6379
    targetPort: ray
    name: ray
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-service
spec:
  type: NodePort
  selector:
    component: head
  ports:
  - protocol: TCP
    port: 8080
    targetPort: vllm
    name: vllm
    nodePort: 30080
