apiVersion: batch/v1
kind: Job
metadata:
  name: test-db-seed
spec:
  template:
    spec:
      containers:
      - name: db-seed
        image: postgres:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          apt-get update && 
          apt-get install -y postgresql-client &&
          /scripts/wait-and-run-pg.sh
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_DB
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        hostPath:
          path: /root/app/backend/scripts
          type: Directory
      restartPolicy: OnFailure
