# db-migration-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: test-db-migrate
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z test-pg-db 5432; do echo waiting for db; sleep 2; done;']
      containers:
      - name: db-migrate
        image: localhost:5000/cpu-test-db-migrate:latest
        env:
        - name: ConnectionStrings__TestContext
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: ConnectionStrings__TestContext
      restartPolicy: OnFailure