# jobs/db-seed-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: test-db-seed
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z test-pg-db 5432; do echo waiting for db; sleep 2; done;']
      containers:
      - name: db-seed
        image: localhost:5000/cpu-test-pg-db-seed:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_DB
      restartPolicy: OnFailure