---
- name: Verify Kubernetes System Setup
  hosts: all
  become: true
  tasks:
    - name: Verify swap is disabled
      shell: swapon --show
      register: swap_status
      failed_when: swap_status.stdout != ""

    - name: Verify fstab has no swap entries
      command: grep -v '^#' /etc/fstab
      register: fstab_content
      failed_when: fstab_content.stdout is search('swap')

    - name: Verify UFW status
      service_facts:
      register: services
      failed_when: 
        - "'ufw.service' in services.ansible_facts.services"
        - "services.ansible_facts.services['ufw.service'].state == 'running'"

    - name: Verify kernel modules are loaded
      shell: lsmod | grep -E 'overlay|br_netfilter'
      register: modules
      failed_when: modules.rc != 0

    - name: Verify sysctl settings
      shell: sysctl -a
      register: sysctl_settings
      failed_when: >
        not (
          'net.bridge.bridge-nf-call-iptables = 1' in sysctl_settings.stdout and
          'net.bridge.bridge-nf-call-ip6tables = 1' in sysctl_settings.stdout and
          'net.ipv4.ip_forward = 1' in sysctl_settings.stdout
        )

    # - name: Verify GPU drivers installation
    #   shell: nvidia-smi
    #   register: nvidia_check
    #   failed_when: nvidia_check.rc != 0