apiVersion: v1
kind: Service
metadata:
 name: testapi
spec:
 type: NodePort
 ports:
 - name: http
   port: 8080
   targetPort: 8080
   nodePort: 31178
 - name: https
   port: 8081
   targetPort: 8081
   nodePort: 30161
 selector:
   app: testapi