# services/ui-service.yaml - Updated targetPort to 80 to match Nginx in our image
apiVersion: v1
kind: Service
metadata:
  name: testui
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: testui