apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapi
  template:
    metadata:
      labels:
        app: testapi
    spec:
      containers:
      - name: testapi
        image: mcr.microsoft.com/dotnet/sdk:9.0
        workingDir: /src/TestApi
        command: ["dotnet"]
        args: ["watch", "run", "--urls", "http://0.0.0.0:8080"]
        ports:
        - containerPort: 8080
        - containerPort: 8081
        env:
        - name: ConnectionStrings__TestContext
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: ConnectionStrings__TestContext
        volumeMounts:
        - name: api-source
          mountPath: /src
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
      volumes:
      - name: api-source
        hostPath:
          path: /root/app/backend
          type: Directory
