apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmaps/api-config.yaml
- configmaps/console-config.yaml
- configmaps/ui-config.yaml
- deployments/api-deployment.yaml
- deployments/console-deployment.yaml
- deployments/db-deployment.yaml
- deployments/ui-deployment.yaml
- jobs/db-migration-job.yaml
- jobs/db-seed-job.yaml
- services/api-service.yaml
- services/db-service.yaml
- services/ui-service.yaml
- networking/ingress.yaml
- networking/network-policies.yaml
- volumes/postgres-pv.yaml
secretGenerator:
- name: api-secrets
  files:
  - ConnectionStrings__TestContext=secrets/connection-string.txt
- name: db-credentials
  literals:
  - POSTGRES_USER=testuser
  - POSTGRES_PASSWORD=testpass
  - POSTGRES_DB=testdb