apiVersion: apps/v1
kind: Deployment
metadata:
  name: testui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testui
  template:
    metadata:
      labels:
        app: testui
    spec:
      containers:
      - name: testui
        image: node:20.18-alpine
        workingDir: /app
        command: ["/bin/sh", "-c"]
        args:
        - |
          corepack enable && 
          corepack prepare pnpm@latest --activate &&
          cd frontend &&
          pnpm install &&
          cd apps/web &&
          pnpm dev --host 0.0.0.0
        ports:
        - containerPort: 3000
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: ui-config
              key: VITE_API_URL
        volumeMounts:
        - name: ui-source
          mountPath: /app
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 15
      volumes:
      - name: ui-source
        hostPath:
          path: /root/app
          type: Directory
