# secrets/api-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  ConnectionStrings__TestContext: "Host=test-pg-db;Port=5432;Database=testdb;Username=testuser;Password=testpass"