apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: vllm-pipeline-
namespace: vllm-offline

resources:
- namespace.yaml
- head-deployment.yaml
- worker-deployment.yaml
- service.yaml

configMapGenerator:
- name: vllm-config
  literals:
  - RAY_PORT=6379
  - VLLM_PORT=8000

commonLabels:
  app.kubernetes.io/name: vllm
  app.kubernetes.io/instance: vllm-offline
