apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      nodeSelector:
        role: worker
      tolerations:
      - key: "role"
        operator: "Equal"
        value: "worker"
        effect: "NoSchedule"
      initContainers:
      - name: wait-for-head
        image: busybox:1.28
        command: ['sh', '-c', 
          'until nslookup vllm-head-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local && nc -z vllm-head-service 6379; do echo waiting for head node; sleep 2; done']
      containers:
      - name: vllm-worker
        image: localhost:5000/vllm-tce:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: huggingface-cache
          mountPath: /root/.cache/huggingface
        - name: code
          mountPath: /vllm-workspace/app
        - name: dshm
          mountPath: /dev/shm
        command:
        - "/bin/sh"
        - "-c"
        - "ray start --address=$(VLLM_HEAD_SERVICE):6379 --block"
        env:
        - name: VLLM_HEAD_SERVICE
          value: vllm-head-service
      volumes:
      - name: huggingface-cache
        hostPath:
          path: /root/.cache/huggingface
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 25Gi
      - name: code
        hostPath:
          path: /root/TCE-Kubernetes-scripts/app
