---
- name: Install and Configure Kubernetes
  hosts: all
  become: true
  
  tasks:
    - name: Create Kubernetes keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
        
    - name: Add Kubernetes GPG key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        dest: /tmp/k8s.gpg
        
    - name: Dearmor GPG key
      shell: cat /tmp/k8s.gpg | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      
    - name: Set permissions for keyring
      file:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        mode: '0644'
        
    - name: Add Kubernetes repository
      copy:
        content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
        dest: /etc/apt/sources.list.d/kubernetes.list
        mode: '0644'
        
    - name: Install Kubernetes packages
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes
        
    - name: Hold Kubernetes packages
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl
        - containerd
        
    - name: Install bash completion
      apt:
        name: bash-completion
        state: present
        
    - name: Set up kubectl bash completion
      shell: |
        kubectl completion bash | tee /etc/bash_completion.d/kubectl > /dev/null
        chmod a+r /etc/bash_completion.d/kubectl
        echo 'source <(kubectl completion bash)' >> ~/.bashrc