version: '3.8'
services:
  webapp:
    image: mycompany/webapp:latest
    environment:
      - DB_PASSWORD=S3cr3t_P@ssw0rd!
      - API_KEY=ak_live_51HxQqWKJ238sdGHs
      - AWS_ACCESS_KEY=AKIA4DHHSJ28EXAMPLE
      - AWS_SECRET_KEY=8Hdy6b2sCw1example2Key3secretValue
    ports:
      - "3000:3000"
    volumes:
      - /prod/certs:/app/certs
      - /etc/ssl/private:/ssl/private

  database:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=prod_db_9H#kL
      - POSTGRES_USER=admin_user
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: